config/routes.rb
Rails.application.routes.draw do
  resources :medicinas
  resources :archivos
  resources :empleados
  resources :pacientes
  resources :pacientes

end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :set_empleado, only: [:show, :edit, :update, :destroy]

  # GET /empleados
  # GET /empleados.json
  def index
    @empleados = Empleado.all
  end

  # GET /empleados/1
  # GET /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
  end

  # GET /empleados/1/edit
  def edit
  end

  # POST /empleados
  # POST /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)

    respond_to do |format|
      if @empleado.save
        format.html { redirect_to @empleado, notice: 'Empleado was successfully created.' }
        format.json { render :show, status: :created, location: @empleado }
      else
        format.html { render :new }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empleados/1
  # PATCH/PUT /empleados/1.json
  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.html { redirect_to @empleado, notice: 'Empleado was successfully updated.' }
        format.json { render :show, status: :ok, location: @empleado }
      else
        format.html { render :edit }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1
  # DELETE /empleados/1.json
  def destroy
    @empleado.destroy
    respond_to do |format|
      format.html { redirect_to empleados_url, notice: 'Empleado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empleado_params
      params.require(:empleado).permit(:nombre, :edad, :puesto, :salario)
    end
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/views/empleados/_form.html.erb
<%= form_for(@empleado) do |f| %>
  <% if @empleado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empleado.errors.count, "error") %> prohibited this empleado from being saved:</h2>

      <ul>
      <% @empleado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :edad %><br>
    <%= f.number_field :edad %>
  </div>
  <div class="field">
    <%= f.label :puesto %><br>
    <%= f.text_field :puesto %>
  </div>
  <div class="field">
    <%= f.label :salario %><br>
    <%= f.number_field :salario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/empleados/edit.html.erb
<h1>Editing Empleado</h1>

<%= render 'form' %>

<%= link_to 'Show', @empleado %> |
<%= link_to 'Back', empleados_path %>

app/views/empleados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Empleados</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Edad</th>
      <th>Puesto</th>
      <th>Salario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empleados.each do |empleado| %>
      <tr>
        <td><%= empleado.nombre %></td>
        <td><%= empleado.edad %></td>
        <td><%= empleado.puesto %></td>
        <td><%= empleado.salario %></td>
        <td><%= link_to 'Show', empleado %></td>
        <td><%= link_to 'Edit', edit_empleado_path(empleado) %></td>
        <td><%= link_to 'Destroy', empleado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empleado', new_empleado_path %>

app/views/empleados/new.html.erb
<h1>New Empleado</h1>

<%= render 'form' %>

<%= link_to 'Back', empleados_path %>

app/views/empleados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @empleado.nombre %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @empleado.edad %>
</p>

<p>
  <strong>Puesto:</strong>
  <%= @empleado.puesto %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @empleado.salario %>
</p>

<%= link_to 'Edit', edit_empleado_path(@empleado) %> |
<%= link_to 'Back', empleados_path %>