config/routes.rb
Rails.application.routes.draw do
  resources :medicinas
  resources :archivos
  resources :empleados
  resources :pacientes
  resources :pacientes

end

app/models/medicina.rb
class Medicina < ActiveRecord::Base
mount_uploader :my_file, FileUploader
end

app/controllers/medicinas_controller.rb
class MedicinasController < ApplicationController
  before_action :set_medicina, only: [:show, :edit, :update, :destroy]

  # GET /medicinas
  # GET /medicinas.json
  def index
    @medicinas = Medicina.all
  end

  # GET /medicinas/1
  # GET /medicinas/1.json
  def show
  end

  # GET /medicinas/new
  def new
    @medicina = Medicina.new
  end

  # GET /medicinas/1/edit
  def edit
  end

  # POST /medicinas
  # POST /medicinas.json
  def create
    @medicina = Medicina.new(medicina_params)
    @medicina.my_file = params[:file]

    respond_to do |format|
      if @medicina.save
        format.html { redirect_to @medicina, notice: 'Medicina was successfully created.' }
        format.json { render :show, status: :created, location: @medicina }
      else
        format.html { render :new }
        format.json { render json: @medicina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicinas/1
  # PATCH/PUT /medicinas/1.json
  def update
    respond_to do |format|
      if @medicina.update(medicina_params)
        format.html { redirect_to @medicina, notice: 'Medicina was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicina }
      else
        format.html { render :edit }
        format.json { render json: @medicina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicinas/1
  # DELETE /medicinas/1.json
  def destroy
    @medicina.destroy
    respond_to do |format|
      format.html { redirect_to medicinas_url, notice: 'Medicina was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicina
      @medicina = Medicina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicina_params
      params.require(:medicina).permit(:my_file)
    end
end

app/helpers/medicinas_helper.rb
module MedicinasHelper
end

app/views/medicinas/_form.html.erb
<%= form_for(@medicina) do |f| %>
  <% if @medicina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medicina.errors.count, "error") %> prohibited this medicina from being saved:</h2>

      <ul>
      <% @medicina.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :my_file %><br>
    <%= f.file_field :my_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medicinas/edit.html.erb
<h1>Editing Medicina</h1>

<%= render 'form' %>

<%= link_to 'Show', @medicina %> |
<%= link_to 'Back', medicinas_path %>

app/views/medicinas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Medicinas</h1>

<table>
  <thead>
    <tr>
      <th>My file</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicinas.each do |medicina| %>
      <tr>
        <td><a href="<%= medicina.my_file %>">Download</a></td>
        <td><%= link_to 'Show', medicina %></td>
        <td><%= link_to 'Edit', edit_medicina_path(medicina) %></td>
        <td><%= link_to 'Destroy', medicina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medicina', new_medicina_path %>

app/views/medicinas/new.html.erb
<h1>New Medicina</h1>

<%= render 'form' %>

<%= link_to 'Back', medicinas_path %>

app/views/medicinas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>My file:</strong>
  <%= @medicina.my_file %>
</p>

<%= link_to 'Edit', edit_medicina_path(@medicina) %> |
<%= link_to 'Back', medicinas_path %>