config/routes.rb
Rails.application.routes.draw do
  resources :medicinas
  resources :archivos
  resources :empleados
  resources :pacientes
  resources :pacientes

end

app/models/archivo.rb
class Archivo < ActiveRecord::Base
mount_uploader :my_file, FileUploader
end

app/controllers/archivos_controller.rb
class ArchivosController < ApplicationController
  before_action :set_archivo, only: [:show, :edit, :update, :destroy]

  # GET /archivos
  # GET /archivos.json
  def index
    @archivos = Archivo.all
  end

  # GET /archivos/1
  # GET /archivos/1.json
  def show
  end

  # GET /archivos/new
  def new
    @archivo = Archivo.new
  end

  # GET /archivos/1/edit
  def edit
  end

  # POST /archivos
  # POST /archivos.json
  def create
    @archivo = Archivo.new(archivo_params)
    @archivo.my_file = params[:file]

    respond_to do |format|
      if @archivo.save
        format.html { redirect_to @archivo, notice: 'Archivo was successfully created.' }
        format.json { render :show, status: :created, location: @archivo }
      else
        format.html { render :new }
        format.json { render json: @archivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archivos/1
  # PATCH/PUT /archivos/1.json
  def update
    respond_to do |format|
      if @archivo.update(archivo_params)
        format.html { redirect_to @archivo, notice: 'Archivo was successfully updated.' }
        format.json { render :show, status: :ok, location: @archivo }
      else
        format.html { render :edit }
        format.json { render json: @archivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archivos/1
  # DELETE /archivos/1.json
  def destroy
    @archivo.destroy
    respond_to do |format|
      format.html { redirect_to archivos_url, notice: 'Archivo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archivo
      @archivo = Archivo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archivo_params
      params.require(:archivo).permit(:my_file)
    end
end

app/helpers/archivos_helper.rb
module ArchivosHelper
end

app/views/archivos/_form.html.erb
<%= form_for(@archivo) do |f| %>
  <% if @archivo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@archivo.errors.count, "error") %> prohibited this archivo from being saved:</h2>

      <ul>
      <% @archivo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :my_file %><br>
    <%= f.file_field :my_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/archivos/edit.html.erb
<h1>Editing Archivo</h1>

<%= render 'form' %>

<%= link_to 'Show', @archivo %> |
<%= link_to 'Back', archivos_path %>

app/views/archivos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Archivos</h1>

<table>
  <thead>
    <tr>
      <th>My file</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archivos.each do |archivo| %>
      <tr>
        <td><a href="<%= archivo.my_file %>">Download</a></td>
        <td><%= link_to 'Show', archivo %></td>
        <td><%= link_to 'Edit', edit_archivo_path(archivo) %></td>
        <td><%= link_to 'Destroy', archivo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Archivo', new_archivo_path %>

app/views/archivos/new.html.erb
<h1>New Archivo</h1>

<%= render 'form' %>

<%= link_to 'Back', archivos_path %>

app/views/archivos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>My file:</strong>
  <%= @archivo.my_file %>
</p>

<%= link_to 'Edit', edit_archivo_path(@archivo) %> |
<%= link_to 'Back', archivos_path %>